apiVersion: v1
kind: Service
metadata:
  name: personnel-restservice-adapter
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
spec:
  selector:
    app: personnel-restservice-adapter
  ports:
    - port: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personnel-restservice-adapter
  labels:
    app: personnel-restservice-adapter
spec:
  replicas: 1
  template:
    metadata:
      name: personnel-restservice-adapter
      labels:
        app: personnel-restservice-adapter
    spec:
      volumes:
        - name: adapter-data
          emptyDir:
            sizeLimit: 1G
      containers:
        - name: personnel-restservice-adapter
          image: fintlabsacr.azurecr.io/fint-personnel-restservice-adapter:${GIT_COMMIT}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /adapter
              name: adapter-data
          envFrom:
            - configMapRef:
                name: fint-environment
            - secretRef:
                name: fake-adapter
          env:
            - name: server.context-path
              value: /adapter
            - name: server.port
              value: '8080'
            - name: security.basic.enabled
              value: 'false'
            - name: fint.personnel.repository
              value: /adapter
            - name: fint.adapter.endpoints.providers.personal
              value: https://alpha.felleskomponent.no/administrasjon/personal/provider
            - name: fint.adapter.endpoints.providers.organisasjon
              value: https://alpha.felleskomponent.no/administrasjon/organisasjon/provider
      restartPolicy: Always
  selector:
    matchLabels:
      app: personnel-restservice-adapter
